name: Ingestión y Limpieza de Datos Automática

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 4' # Se ejecuta diario (opcional)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Ejecutar script de ingesta (EA1)
      run: python src/ingestion.py

    - name: Ejecutar script de limpieza (EA2)
      run: python src/cleaning.py

    - name: Subir artefactos (Evidencias completas)
      uses: actions/upload-artifact@v4
      with:
        name: evidencias-proyecto-completo
        path: |
          src/db/
          src/static/auditoria/
          src/xlsx/
